config/routes.rb
Rails.application.routes.draw do
  get '/tags' => 'tags#index'
  get '/tags/:id' => 'tags#show', as: :tag
  get '/destinations/:id' => 'destinations#show', as: :destination
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :destinations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def show
    @destination = Destination.find(params[:id])
  end
  def edit
    @destination = Destination.find(params[:id])
  end
  def update
    @destination = Destination.find(params[:id])
    if @destination.update_attributes(destination_params)
      redirect_to(:action => 'show',:id => @destination.id)
    else
      render 'edit'
    end
  end
  private
    def destination_params
      params.require(:destination).permit(:name,:description)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index 
    @tags = Tag.all
  end
  def show
    @tag = Tag.find(params[:id])
    @destinations = @tag.destinations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/destinations/show.html.erb
<div class="container">
  <img src="<%= @destination.image %>" />
  <h3><%= @destination.name%></h3>
  <p><%= @destination.description %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<% @tags.each do |tag|%>
<div class="card">
  <img src="<%=tag.image%>">
  <h2><%= tag.title %></h2>
  <%= link_to "Learn More...", tag_path(tag)%>
</div>
<% end %>

app/views/tags/show.html.erb
<div class="main">
  <div class="container">
    <% @destinations.each do |destination| %>
      <div>
        <img src="<%= destination.image %>">
        <h3><%= destination.name %></h3>
        <p><%= destination.description %></p>
        <%= link_to "Show more", destination_path(destination) %>
      </div>
    <% end %>
  </div>
</div>